from __future__ import annotations


class UiIntent:
    """String constants for GUI intents emitted by view components."""

    # Course list intents
    COURSE_CONFIRM_SELECTION = "course.confirm_selection"
    COURSE_HOVER_SELECT = "course.hover_select"
    COURSE_KEYBOARD_NAVIGATION = "course.keyboard_navigation"
    COURSE_HOME = "course.home"
    COURSE_END = "course.end"

    # Grid intents
    GRID_TOGGLE_COLUMN_SELECTION = "grid.toggle_column_selection"
    GRID_TOGGLE_ROW_EXPAND = "grid.toggle_row_expand"
    GRID_COMMIT_CELL = "grid.commit_cell"
    GRID_EDITOR_FOCUS_IN = "grid.editor_focus_in"
    GRID_EDITOR_FOCUS_OUT = "grid.editor_focus_out"
    GRID_ENTER = "grid.enter"
    GRID_NAV_UP = "grid.nav_up"
    GRID_NAV_DOWN = "grid.nav_down"
    GRID_NAV_LEFT = "grid.nav_left"
    GRID_NAV_RIGHT = "grid.nav_right"
    GRID_DELETE_CELL = "grid.delete_cell"
    GRID_HOME = "grid.home"
    GRID_END = "grid.end"
    GRID_CELL_CLICK = "grid.cell_click"
    GRID_DATE_CELL_CLICK = "grid.date_cell_click"
    GRID_COLUMN_CLICK = "grid.column_click"

    # Toolbar intents
    TOOLBAR_NEW = "toolbar.new"
    TOOLBAR_REFRESH = "toolbar.refresh"
    TOOLBAR_UNDO = "toolbar.undo"
    TOOLBAR_REDO = "toolbar.redo"
    EDIT_UNDO_TO_RECENT_INDEX = "edit.undo_to_recent_index"
    TOOLBAR_PLAN = "toolbar.plan"
    TOOLBAR_EXTEND_TO_VACATION = "toolbar.extend_to_vacation"
    TOOLBAR_AUSFALL = "toolbar.ausfall"
    TOOLBAR_HOSPITATION = "toolbar.hospitation"
    TOOLBAR_LZK = "toolbar.lzk"
    TOOLBAR_LZK_EXPECTED_HORIZON = "toolbar.lzk_expected_horizon"
    TOOLBAR_COPY = "toolbar.copy"
    TOOLBAR_PASTE = "toolbar.paste"
    TOOLBAR_FIND = "toolbar.find"
    TOOLBAR_CLEAR = "toolbar.clear"
    TOOLBAR_RENAME = "toolbar.rename"
    TOOLBAR_SPLIT = "toolbar.split"
    TOOLBAR_MERGE = "toolbar.merge"
    TOOLBAR_RESUME = "toolbar.resume"
    TOOLBAR_MOVE_COLUMNS = "toolbar.move_columns"
    TOOLBAR_EXPORT_AS = "toolbar.export_as"

    # Other view-level intents used in ScreenBuilder
    OPEN_SETTINGS = "app.open_settings"
    REBUILD_LESSON_INDEX = "app.rebuild_lesson_index"
    SHOW_SHADOW_LESSONS = "app.show_shadow_lessons"
    CLOSE_DETAIL_VIEW = "detail.close"
    SET_ROW_MODE = "detail.set_row_mode"
    TOGGLE_AUTO_ROW_MODE = "detail.toggle_auto_row_mode"
    TOGGLE_EXPAND_MODE = "detail.toggle_expand_mode"
    MARK_SELECTED_AS_UB = "detail.mark_selected_as_ub"
    TOGGLE_RESUME_OR_UB = "detail.toggle_resume_or_ub"
    SHOW_UB_ACHIEVEMENTS = "detail.show_ub_achievements"
    SHOW_SHORTCUT_OVERVIEW = "detail.show_shortcut_overview"
    OPEN_COLUMN_VISIBILITY_SETTINGS = "detail.open_column_visibility_settings"

    # Global shortcut and pointer intents
    SHORTCUT_DETAIL_LEFT = "shortcut.detail_left"
    SHORTCUT_DETAIL_RIGHT = "shortcut.detail_right"
    SHORTCUT_DETAIL_LEFT_ALL = "shortcut.detail_left_all"
    SHORTCUT_DETAIL_RIGHT_ALL = "shortcut.detail_right_all"
    SHORTCUT_ESCAPE = "shortcut.escape"
    SHORTCUT_COMMIT_EDIT = "shortcut.commit_edit"
    SHORTCUT_COMMIT_COLUMN = "shortcut.commit_column"
    SHORTCUT_EXPAND_SELECTED_ROW = "shortcut.expand_selected_row"
    SHORTCUT_COLLAPSE_SELECTED_ROW = "shortcut.collapse_selected_row"
    SHORTCUT_CUT = "shortcut.cut"
    SHORTCUT_COPY = "shortcut.copy"
    SHORTCUT_PASTE = "shortcut.paste"
    GLOBAL_CLICK_COMMIT_CELL = "global.click_commit_cell"
